### ISSUE TITLE
Monitoring regions

### ISSUE THREAD

**Issue by JMCPH** [mpurbo/MMPReactiveCoreLocation#4]
Hi!

I'm having 2 questions:
1. How i'm i able to get a list of the monitored regions? (Normally: locationmanager.monitoredregions.count)
2. How can i set the MMPEventtype for a region (I want to make a notification onEnter)

**Comment by mpurbo** [comment]
Hi JakobPip,
1. You could get the underlying CLLocationManager instance by calling `locationManager` method, but you will need to assign the instance of `MMPReactiveCoreLocation` to a variable _before_ subscribing to any signal. Something like:
   
   ``` objc
   // here you create the instance
   MMPReactiveCoreLocation *service = [[[MMPReactiveCoreLocation service] region:region1] region:region2];
   // you may subscribe to a signal now
   [[service regionEvents] subscribeNext:^(MMPRegionEvent *regionEvent) {
       // do something with the event...
   }];
   
   //... somewhere else, you could use service variable to access the underlying CLLocationManager
   id regions = service.locationManager.monitoredRegions;
   ```
2. Did you mean that you want to get notified when an entrance to a region detected? (i.e. the equivalent of standard delegate's `locationManager:didEnterRegion:`). If that's the question, then you could filter regionEvents signal and only pass the events when the type equals to `MMPRegionEventTypeRegionEnter` and the region is that region you're interested in.
